name: Deploy Node Server

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      
      - name: Build DOcker Image
        run: docker build -t tanmaynewatia/arva-health-cafe-task .

      - name: Publish Image to docker hub
        run: docker push tanmaynewatia/arva-health-cafe-task:latest
  
  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from docker hub
        run: docker pull tanmaynewatia/arva-health-cafe-task:latest

      - name: Run Docker COntainer
        run: docker run -d -p 4000:4000 --name nodejs-app-container -e ATLAS_URI='${{secrets.ATLAS_URI}}' tanmaynewatia/arva-health-cafe-task